// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel CSSecond

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWStructuredBuffer<float> floatsData;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	floatsData[id.x] = id.x;

}

[numthreads(64, 1, 1)]
void CSSecond (uint3 id : SV_DispatchThreadID)
{
	floatsData[id.x] = floatsData[id.x] * 2;
}
